### ISSUE TITLE
Spans for middleware are missing.

### ISSUE THREAD

**Issue by mickeyinfoshan** [zcong1993/opentelemetry-instrumentation-egg#56]
![image](https://user-images.githubusercontent.com/6109925/201589205-22ad1965-fcae-455c-9090-2fcc0b990d6c.png)

I'm expecting traces for all spans of my egg application. What I got is just http client requests.

**Comment by zcong1993** [comment]
you can tweak `ignoreLayers` config, please follow this docs, https://github.com/zcong1993/opentelemetry-instrumentation-egg#egg-instrumentation-options

**Comment by mickeyinfoshan** [comment]
I've tried override the `ignoreLayers` to be `[]`, but it doesn't work neither.
What I found is that `opentelemetry-instrumentation-egg` doesn't work at all. The patch function, which a breakpoint was been added to, has never been invoked.
![image](https://user-images.githubusercontent.com/6109925/201606836-48376367-79e9-4f46-82fe-50689a2cfebe.png)
My egg application is started by `egg-bin` or `egg-scripts` and my `app.ts` is like this:


```ts
import * as os from 'os';
import { NodeTracerProvider } from '@opentelemetry/node';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { EggInstrumentation } from 'opentelemetry-instrumentation-egg';
import { Resource } from '@opentelemetry/resources';
import {
  SemanticResourceAttributes,
} from '@opentelemetry/semantic-conventions';

import {
  SimpleSpanProcessor,
  ConsoleSpanExporter,
} from '@opentelemetry/tracing';

const provider = new NodeTracerProvider({
  // @ts-ignore
  resource: new Resource({
    [SemanticResourceAttributes.HOST_NAME]: os.hostname(),
  }),
});

provider.register();

registerInstrumentations({
  instrumentations: [
    // Egg instrumentation expects HTTP layer to be instrumented
    new HttpInstrumentation(),
    // @ts-ignore
    new EggInstrumentation({
      ignoreLayers: [],
    }),
  ],
});

export default class AppBoot {}
```

**Comment by zcong1993** [comment]
please create a reproduction repo.

**Comment by zcong1993** [comment]
I try to reproduction it locally, but it works fine. Is this expected? @mickeyinfoshan 

<img width="1907" alt="image" src="https://user-images.githubusercontent.com/18305255/201645891-85ec8def-1f92-4ddc-b4fa-9c482d60b4c1.png">

**Comment by mickeyinfoshan** [comment]
![image](https://user-images.githubusercontent.com/6109925/202071945-3a9f8ca2-9679-4c9c-9a20-1cdd2203f777.png)
I just used the demo code provided and it didn't work neither. My node version is `v16.15.1`.

**Comment by zcong1993** [comment]
Did you follow the readme step to start server? and you should see the trace init logs:

```
npm run tsc
source .envrc
node start.js
[trace] initialized
egg start at 7001
```
